<?php

namespace Database\Seeders;

use App\Models\Destination;
use App\Models\Province;
use Illuminate\Database\Seeder;

class EkowisataDestinationsSeeder extends Seeder
{
    public function run(): void
    {
        // Create provinces if not exists
        $provinces = [
            ['id' => 11, 'name' => 'Aceh', 'capital' => 'Banda Aceh', 'island' => 'Sumatera'],
            ['id' => 12, 'name' => 'Sumatera Utara', 'capital' => 'Medan', 'island' => 'Sumatera'],
            ['id' => 13, 'name' => 'Sumatera Barat', 'capital' => 'Padang', 'island' => 'Sumatera'],
            ['id' => 14, 'name' => 'Riau', 'capital' => 'Pekanbaru', 'island' => 'Sumatera'],
            ['id' => 15, 'name' => 'Jambi', 'capital' => 'Jambi', 'island' => 'Sumatera'],
            ['id' => 16, 'name' => 'Sumatera Selatan', 'capital' => 'Palembang', 'island' => 'Sumatera'],
            ['id' => 17, 'name' => 'Bengkulu', 'capital' => 'Bengkulu', 'island' => 'Sumatera'],
            ['id' => 18, 'name' => 'Lampung', 'capital' => 'Bandar Lampung', 'island' => 'Sumatera'],
            ['id' => 19, 'name' => 'Bangka Belitung', 'capital' => 'Pangkal Pinang', 'island' => 'Sumatera'],
            ['id' => 21, 'name' => 'Kepulauan Riau', 'capital' => 'Tanjung Pinang', 'island' => 'Sumatera'],
            ['id' => 31, 'name' => 'DKI Jakarta', 'capital' => 'Jakarta', 'island' => 'Jawa'],
            ['id' => 32, 'name' => 'Jawa Barat', 'capital' => 'Bandung', 'island' => 'Jawa'],
            ['id' => 33, 'name' => 'Jawa Tengah', 'capital' => 'Semarang', 'island' => 'Jawa'],
            ['id' => 34, 'name' => 'DI Yogyakarta', 'capital' => 'Yogyakarta', 'island' => 'Jawa'],
            ['id' => 35, 'name' => 'Jawa Timur', 'capital' => 'Surabaya', 'island' => 'Jawa'],
            ['id' => 36, 'name' => 'Banten', 'capital' => 'Serang', 'island' => 'Jawa'],
            ['id' => 51, 'name' => 'Bali', 'capital' => 'Denpasar', 'island' => 'Bali'],
            ['id' => 52, 'name' => 'Nusa Tenggara Barat', 'capital' => 'Mataram', 'island' => 'Nusa Tenggara'],
            ['id' => 53, 'name' => 'Nusa Tenggara Timur', 'capital' => 'Kupang', 'island' => 'Nusa Tenggara'],
            ['id' => 61, 'name' => 'Kalimantan Barat', 'capital' => 'Pontianak', 'island' => 'Kalimantan'],
            ['id' => 62, 'name' => 'Kalimantan Tengah', 'capital' => 'Palangkaraya', 'island' => 'Kalimantan'],
            ['id' => 63, 'name' => 'Kalimantan Selatan', 'capital' => 'Banjarmasin', 'island' => 'Kalimantan'],
            ['id' => 64, 'name' => 'Kalimantan Timur', 'capital' => 'Samarinda', 'island' => 'Kalimantan'],
            ['id' => 65, 'name' => 'Kalimantan Utara', 'capital' => 'Tanjung Selor', 'island' => 'Kalimantan'],
            ['id' => 71, 'name' => 'Sulawesi Utara', 'capital' => 'Manado', 'island' => 'Sulawesi'],
            ['id' => 72, 'name' => 'Sulawesi Tengah', 'capital' => 'Palu', 'island' => 'Sulawesi'],
            ['id' => 73, 'name' => 'Sulawesi Selatan', 'capital' => 'Makassar', 'island' => 'Sulawesi'],
            ['id' => 74, 'name' => 'Sulawesi Tenggara', 'capital' => 'Kendari', 'island' => 'Sulawesi'],
            ['id' => 75, 'name' => 'Gorontalo', 'capital' => 'Gorontalo', 'island' => 'Sulawesi'],
            ['id' => 76, 'name' => 'Sulawesi Barat', 'capital' => 'Mamuju', 'island' => 'Sulawesi'],
            ['id' => 81, 'name' => 'Maluku', 'capital' => 'Ambon', 'island' => 'Maluku'],
            ['id' => 82, 'name' => 'Maluku Utara', 'capital' => 'Ternate', 'island' => 'Maluku'],
            ['id' => 91, 'name' => 'Papua Barat', 'capital' => 'Manokwari', 'island' => 'Papua'],
            ['id' => 94, 'name' => 'Papua', 'capital' => 'Jayapura', 'island' => 'Papua'],
        ];

        foreach ($provinces as $prov) {
            Province::updateOrCreate(
                ['id' => $prov['id']], 
                ['name' => $prov['name'], 'capital' => $prov['capital'], 'island' => $prov['island']]
            );
        }

        // 42 Ecotourism Destinations across Indonesia
        $destinations = [
            // SUMATERA (8 lokasi)
            [
                'name' => 'Danau Toba',
                'slug' => 'danau-toba',
                'province_id' => 12,
                'category' => 'Danau',
                'description' => 'Danau vulkanik terbesar di dunia dengan Pulau Samosir di tengahnya. Keindahan alam dan kekayaan budaya Batak menjadikannya destinasi ekowisata unggulan.',
                'location' => 'Sumatera Utara',
                'latitude' => 2.6845,
                'longitude' => 98.8756,
                'price' => 150000,
                'quota_per_day' => 500,
                'rating' => 4.8,
                'status' => 'Active',
            ],
            [
                'name' => 'Bukit Lawang Orangutan Sanctuary',
                'slug' => 'bukit-lawang',
                'province_id' => 12,
                'category' => 'Hutan',
                'description' => 'Pusat rehabilitasi orangutan di Taman Nasional Gunung Leuser. Tempat terbaik untuk melihat orangutan liar di habitat aslinya.',
                'location' => 'Langkat, Sumatera Utara',
                'latitude' => 3.5560,
                'longitude' => 98.1303,
                'price' => 350000,
                'quota_per_day' => 100,
                'rating' => 4.9,
                'status' => 'Active',
            ],
            [
                'name' => 'Pulau Weh',
                'slug' => 'pulau-weh',
                'province_id' => 11,
                'category' => 'Laut',
                'description' => 'Surga diving di ujung barat Indonesia. Terkenal dengan titik KM 0 Indonesia dan keindahan terumbu karangnya.',
                'location' => 'Sabang, Aceh',
                'latitude' => 5.8269,
                'longitude' => 95.2734,
                'price' => 200000,
                'quota_per_day' => 200,
                'rating' => 4.7,
                'status' => 'Active',
            ],
            [
                'name' => 'Danau Maninjau',
                'slug' => 'danau-maninjau',
                'province_id' => 13,
                'category' => 'Danau',
                'description' => 'Danau vulkanik dengan 44 tikungan legendaris menuju lokasi. Keindahan alam yang masih asri dengan budaya Minangkabau.',
                'location' => 'Agam, Sumatera Barat',
                'latitude' => -0.3114,
                'longitude' => 100.1894,
                'price' => 75000,
                'quota_per_day' => 300,
                'rating' => 4.6,
                'status' => 'Active',
            ],
            [
                'name' => 'Taman Nasional Kerinci Seblat',
                'slug' => 'tn-kerinci-seblat',
                'province_id' => 15,
                'category' => 'Hutan',
                'description' => 'Taman nasional terbesar di Sumatera, rumah bagi harimau Sumatera dan Gunung Kerinci tertinggi di Sumatera.',
                'location' => 'Jambi',
                'latitude' => -2.0854,
                'longitude' => 101.2641,
                'price' => 300000,
                'quota_per_day' => 150,
                'rating' => 4.7,
                'status' => 'Active',
            ],
            [
                'name' => 'Pulau Bangka',
                'slug' => 'pulau-bangka',
                'province_id' => 19,
                'category' => 'Pantai',
                'description' => 'Pantai-pantai eksotis dengan batu granit raksasa yang unik. Destinasi ekowisata bahari yang masih alami.',
                'location' => 'Bangka Belitung',
                'latitude' => -2.1194,
                'longitude' => 106.1169,
                'price' => 100000,
                'quota_per_day' => 400,
                'rating' => 4.5,
                'status' => 'Active',
            ],
            [
                'name' => 'Way Kambas National Park',
                'slug' => 'way-kambas',
                'province_id' => 18,
                'category' => 'Hutan',
                'description' => 'Pusat konservasi gajah Sumatera dan badak Sumatera. Safari gajah dan melihat satwa liar di alam bebas.',
                'location' => 'Lampung Timur',
                'latitude' => -4.9306,
                'longitude' => 105.7708,
                'price' => 250000,
                'quota_per_day' => 200,
                'rating' => 4.6,
                'status' => 'Active',
            ],
            [
                'name' => 'Pulau Mentawai',
                'slug' => 'pulau-mentawai',
                'province_id' => 13,
                'category' => 'Pantai',
                'description' => 'Surga surfing dengan ombak kelas dunia dan budaya suku Mentawai yang unik. Ekowisata budaya dan bahari.',
                'location' => 'Kepulauan Mentawai',
                'latitude' => -1.4232,
                'longitude' => 99.0674,
                'price' => 500000,
                'quota_per_day' => 100,
                'rating' => 4.8,
                'status' => 'Active',
            ],

            // JAWA (10 lokasi)
            [
                'name' => 'Gunung Bromo',
                'slug' => 'gunung-bromo',
                'province_id' => 35,
                'category' => 'Gunung',
                'description' => 'Gunung berapi aktif dengan pemandangan matahari terbit spektakuler. Ikon wisata alam Jawa Timur yang mendunia.',
                'location' => 'Probolinggo, Jawa Timur',
                'latitude' => -7.9425,
                'longitude' => 112.9531,
                'price' => 320000,
                'quota_per_day' => 600,
                'rating' => 4.9,
                'status' => 'Active',
            ],
            [
                'name' => 'Candi Borobudur',
                'slug' => 'candi-borobudur',
                'province_id' => 33,
                'category' => 'Budaya',
                'description' => 'Candi Buddha terbesar di dunia, warisan budaya UNESCO. Arsitektur megah dengan relief tentang ajaran Buddha.',
                'location' => 'Magelang, Jawa Tengah',
                'latitude' => -7.6079,
                'longitude' => 110.2038,
                'price' => 375000,
                'quota_per_day' => 800,
                'rating' => 4.9,
                'status' => 'Active',
            ],
            [
                'name' => 'Kawah Ijen',
                'slug' => 'kawah-ijen',
                'province_id' => 35,
                'category' => 'Gunung',
                'description' => 'Fenomena blue fire yang langka dan danau kawah asam terbesar di dunia. Trekking dengan pemandangan menakjubkan.',
                'location' => 'Banyuwangi, Jawa Timur',
                'latitude' => -8.0580,
                'longitude' => 114.2421,
                'price' => 150000,
                'quota_per_day' => 400,
                'rating' => 4.8,
                'status' => 'Active',
            ],
            [
                'name' => 'Taman Nasional Ujung Kulon',
                'slug' => 'tn-ujung-kulon',
                'province_id' => 36,
                'category' => 'Hutan',
                'description' => 'Habitat terakhir badak Jawa satu-satunya di dunia. Hutan hujan tropis dataran rendah dan pantai eksotis.',
                'location' => 'Pandeglang, Banten',
                'latitude' => -6.7608,
                'longitude' => 105.3376,
                'price' => 350000,
                'quota_per_day' => 100,
                'rating' => 4.7,
                'status' => 'Active',
            ],
            [
                'name' => 'Kepulauan Karimunjawa',
                'slug' => 'karimunjawa',
                'province_id' => 33,
                'category' => 'Laut',
                'description' => 'Kepulauan dengan 27 pulau yang indah. Snorkeling, diving, dan pantai berpasir putih yang masih alami.',
                'location' => 'Jepara, Jawa Tengah',
                'latitude' => -5.8609,
                'longitude' => 110.4619,
                'price' => 450000,
                'quota_per_day' => 300,
                'rating' => 4.7,
                'status' => 'Active',
            ],
            [
                'name' => 'Dieng Plateau',
                'slug' => 'dieng-plateau',
                'province_id' => 33,
                'category' => 'Gunung',
                'description' => 'Dataran tinggi dengan candi-candi Hindu tertua di Jawa. Fenomena telaga warna dan sunrise spektakuler.',
                'location' => 'Wonosobo, Jawa Tengah',
                'latitude' => -7.2025,
                'longitude' => 109.9087,
                'price' => 200000,
                'quota_per_day' => 500,
                'rating' => 4.6,
                'status' => 'Active',
            ],
            [
                'name' => 'Gunung Gede Pangrango',
                'slug' => 'gunung-gede-pangrango',
                'province_id' => 32,
                'category' => 'Gunung',
                'description' => 'Taman nasional dengan keanekaragaman hayati tinggi. Trekking ke puncak dengan pemandangan fantastis.',
                'location' => 'Cianjur, Jawa Barat',
                'latitude' => -6.7320,
                'longitude' => 106.9780,
                'price' => 150000,
                'quota_per_day' => 300,
                'rating' => 4.6,
                'status' => 'Active',
            ],
            [
                'name' => 'Pantai Pangandaran',
                'slug' => 'pantai-pangandaran',
                'province_id' => 32,
                'category' => 'Pantai',
                'description' => 'Pantai dengan dua sisi menghadap laut. Cagar alam dengan satwa liar dan gua-gua alami.',
                'location' => 'Pangandaran, Jawa Barat',
                'latitude' => -7.6884,
                'longitude' => 108.6502,
                'price' => 100000,
                'quota_per_day' => 1000,
                'rating' => 4.5,
                'status' => 'Active',
            ],
            [
                'name' => 'Goa Jomblang',
                'slug' => 'goa-jomblang',
                'province_id' => 34,
                'category' => 'Hutan',
                'description' => 'Goa vertikal dengan cahaya surga yang menembus. Caving adventure dengan pemandangan alam bawah tanah.',
                'location' => 'Gunung Kidul, Yogyakarta',
                'latitude' => -7.9621,
                'longitude' => 110.3395,
                'price' => 500000,
                'quota_per_day' => 150,
                'rating' => 4.8,
                'status' => 'Active',
            ],
            [
                'name' => 'Pulau Sempu',
                'slug' => 'pulau-sempu',
                'province_id' => 35,
                'category' => 'Pantai',
                'description' => 'Cagar alam dengan Segara Anakan yang indah. Trekking dan camping di pulau tak berpenghuni.',
                'location' => 'Malang, Jawa Timur',
                'latitude' => -8.4508,
                'longitude' => 112.6922,
                'price' => 50000,
                'quota_per_day' => 100,
                'rating' => 4.7,
                'status' => 'Active',
            ],

            // BALI & NUSA TENGGARA (6 lokasi)
            [
                'name' => 'West Bali National Park',
                'slug' => 'west-bali-national-park',
                'province_id' => 51,
                'category' => 'Hutan',
                'description' => 'Taman nasional satu-satunya di Bali, habitat jalak Bali yang langka. Mangrove, savana, dan terumbu karang.',
                'location' => 'Jembrana, Bali',
                'latitude' => -8.1510,
                'longitude' => 114.4426,
                'price' => 200000,
                'quota_per_day' => 300,
                'rating' => 4.6,
                'status' => 'Active',
            ],
            [
                'name' => 'Tegallalang Rice Terraces',
                'slug' => 'tegallalang-rice-terraces',
                'province_id' => 51,
                'category' => 'Budaya',
                'description' => 'Sawah terasering dengan sistem irigasi subak warisan UNESCO. Keindahan lanskap hijau Bali yang ikonik.',
                'location' => 'Ubud, Bali',
                'latitude' => -8.4395,
                'longitude' => 115.2620,
                'price' => 150000,
                'quota_per_day' => 800,
                'rating' => 4.7,
                'status' => 'Active',
            ],
            [
                'name' => 'Gunung Rinjani',
                'slug' => 'gunung-rinjani',
                'province_id' => 52,
                'category' => 'Gunung',
                'description' => 'Gunung tertinggi kedua di Indonesia dengan Danau Segara Anak. Trekking menantang dengan pemandangan luar biasa.',
                'location' => 'Lombok, NTB',
                'latitude' => -8.4114,
                'longitude' => 116.4574,
                'price' => 600000,
                'quota_per_day' => 200,
                'rating' => 4.9,
                'status' => 'Active',
            ],
            [
                'name' => 'Taman Nasional Komodo',
                'slug' => 'tn-komodo',
                'province_id' => 53,
                'category' => 'Hutan',
                'description' => 'Habitat komodo, kadal terbesar di dunia. World Heritage Site dengan keindahan Padar Island dan Pink Beach.',
                'location' => 'Labuan Bajo, NTT',
                'latitude' => -8.5455,
                'longitude' => 119.4892,
                'price' => 700000,
                'quota_per_day' => 400,
                'rating' => 4.9,
                'status' => 'Active',
            ],
            [
                'name' => 'Pink Beach',
                'slug' => 'pink-beach-komodo',
                'province_id' => 53,
                'category' => 'Pantai',
                'description' => 'Salah satu dari 7 pantai pink di dunia. Pasir merah muda unik hasil pecahan karang dan snorkeling spektakuler.',
                'location' => 'Labuan Bajo, NTT',
                'latitude' => -8.5297,
                'longitude' => 119.5908,
                'price' => 300000,
                'quota_per_day' => 200,
                'rating' => 4.8,
                'status' => 'Active',
            ],
            [
                'name' => 'Gili Islands',
                'slug' => 'gili-islands',
                'province_id' => 52,
                'category' => 'Laut',
                'description' => 'Tiga pulau eksotis tanpa kendaraan bermotor. Snorkeling dengan penyu, diving, dan pantai yang tenang.',
                'location' => 'Lombok Utara, NTB',
                'latitude' => -8.3568,
                'longitude' => 116.0455,
                'price' => 250000,
                'quota_per_day' => 600,
                'rating' => 4.7,
                'status' => 'Active',
            ],

            // KALIMANTAN (6 lokasi)
            [
                'name' => 'Tanjung Puting National Park',
                'slug' => 'tanjung-puting',
                'province_id' => 62,
                'category' => 'Hutan',
                'description' => 'Habitat terbesar orangutan di alam liar. Kelotok cruise menyusuri sungai dengan orangutan dan bekantan.',
                'location' => 'Kotawaringin Barat, Kalteng',
                'latitude' => -2.8456,
                'longitude' => 111.6929,
                'price' => 800000,
                'quota_per_day' => 100,
                'rating' => 4.9,
                'status' => 'Active',
            ],
            [
                'name' => 'Danau Sentarum',
                'slug' => 'danau-sentarum',
                'province_id' => 61,
                'category' => 'Danau',
                'description' => 'Danau musiman terbesar di Asia Tenggara. Rumah bagi orangutan dan ratusan spesies ikan air tawar.',
                'location' => 'Kapuas Hulu, Kalbar',
                'latitude' => 0.8167,
                'longitude' => 112.0083,
                'price' => 400000,
                'quota_per_day' => 80,
                'rating' => 4.6,
                'status' => 'Active',
            ],
            [
                'name' => 'Pulau Derawan',
                'slug' => 'pulau-derawan',
                'province_id' => 64,
                'category' => 'Laut',
                'description' => 'Surga diving dengan danau ubur-ubur tak menyengat di Kakaban. Penyu bertelur dan terumbu karang yang indah.',
                'location' => 'Berau, Kalimantan Timur',
                'latitude' => 2.2815,
                'longitude' => 118.2454,
                'price' => 550000,
                'quota_per_day' => 200,
                'rating' => 4.8,
                'status' => 'Active',
            ],
            [
                'name' => 'Pulau Maratua',
                'slug' => 'pulau-maratua',
                'province_id' => 64,
                'category' => 'Laut',
                'description' => 'Pulau terluar dengan laguna dan resort eksklusif. Diving kelas dunia dan keindahan alam yang masih perawan.',
                'location' => 'Berau, Kalimantan Timur',
                'latitude' => 2.1531,
                'longitude' => 118.6222,
                'price' => 750000,
                'quota_per_day' => 100,
                'rating' => 4.9,
                'status' => 'Active',
            ],
            [
                'name' => 'Bukit Baka Bukit Raya',
                'slug' => 'bukit-baka-raya',
                'province_id' => 62,
                'category' => 'Hutan',
                'description' => 'Pegunungan di jantung Kalimantan dengan hutan hujan primer. Rumah bagi ratusan spesies endemik.',
                'location' => 'Kalimantan Tengah',
                'latitude' => -0.8500,
                'longitude' => 112.3500,
                'price' => 350000,
                'quota_per_day' => 50,
                'rating' => 4.5,
                'status' => 'Active',
            ],
            [
                'name' => 'Sungai Mahakam',
                'slug' => 'sungai-mahakam',
                'province_id' => 64,
                'category' => 'Danau',
                'description' => 'Sungai terpanjang kedua di Indonesia. Cruise untuk melihat orangutan, bekantan, dan pesut mahakam.',
                'location' => 'Kalimantan Timur',
                'latitude' => -0.5022,
                'longitude' => 117.1536,
                'price' => 450000,
                'quota_per_day' => 80,
                'rating' => 4.6,
                'status' => 'Active',
            ],

            // SULAWESI (6 lokasi)
            [
                'name' => 'Bunaken National Park',
                'slug' => 'bunaken',
                'province_id' => 71,
                'category' => 'Laut',
                'description' => 'Taman laut dengan biodiversitas tertinggi di dunia. Diving dan snorkeling dengan visibilitas hingga 40 meter.',
                'location' => 'Manado, Sulawesi Utara',
                'latitude' => 1.6174,
                'longitude' => 124.7631,
                'price' => 350000,
                'quota_per_day' => 400,
                'rating' => 4.9,
                'status' => 'Active',
            ],
            [
                'name' => 'Tana Toraja',
                'slug' => 'tana-toraja',
                'province_id' => 73,
                'category' => 'Budaya',
                'description' => 'Warisan budaya dengan upacara pemakaman unik dan rumah tongkonan. Lanskap pegunungan yang memukau.',
                'location' => 'Toraja Utara, Sulawesi Selatan',
                'latitude' => -2.9745,
                'longitude' => 119.8450,
                'price' => 300000,
                'quota_per_day' => 300,
                'rating' => 4.8,
                'status' => 'Active',
            ],
            [
                'name' => 'Wakatobi National Park',
                'slug' => 'wakatobi',
                'province_id' => 74,
                'category' => 'Laut',
                'description' => 'Pusat Segitiga Karang dunia dengan 750 spesies karang. Diving premium dengan keragaman biota laut tertinggi.',
                'location' => 'Wakatobi, Sulawesi Tenggara',
                'latitude' => -5.4818,
                'longitude' => 123.7680,
                'price' => 600000,
                'quota_per_day' => 150,
                'rating' => 4.9,
                'status' => 'Active',
            ],
            [
                'name' => 'Kepulauan Togean',
                'slug' => 'kepulauan-togean',
                'province_id' => 72,
                'category' => 'Laut',
                'description' => 'Kepulauan dengan tiga jenis terumbu karang lengkap. Surga tersembunyi dengan danau ubur-ubur.',
                'location' => 'Tojo Una-Una, Sulawesi Tengah',
                'latitude' => -0.3833,
                'longitude' => 121.8333,
                'price' => 500000,
                'quota_per_day' => 100,
                'rating' => 4.7,
                'status' => 'Active',
            ],
            [
                'name' => 'Lore Lindu National Park',
                'slug' => 'lore-lindu',
                'province_id' => 72,
                'category' => 'Hutan',
                'description' => 'Taman nasional dengan megalit misterius dan anoa. Keanekaragaman burung dan kupu-kupu yang tinggi.',
                'location' => 'Poso, Sulawesi Tengah',
                'latitude' => -1.4472,
                'longitude' => 120.1822,
                'price' => 250000,
                'quota_per_day' => 100,
                'rating' => 4.6,
                'status' => 'Active',
            ],
            [
                'name' => 'Danau Poso',
                'slug' => 'danau-poso',
                'province_id' => 72,
                'category' => 'Danau',
                'description' => 'Danau terdalam ketiga di Indonesia. Kejernihan air dan keindahan alam pegunungan sekitarnya.',
                'location' => 'Poso, Sulawesi Tengah',
                'latitude' => -1.9000,
                'longitude' => 120.6500,
                'price' => 100000,
                'quota_per_day' => 300,
                'rating' => 4.5,
                'status' => 'Active',
            ],

            // MALUKU (4 lokasi)
            [
                'name' => 'Banda Islands',
                'slug' => 'kepulauan-banda',
                'province_id' => 81,
                'category' => 'Laut',
                'description' => 'Kepulauan rempah bersejarah dengan keindahan bawah laut. Diving, snorkeling, dan wisata sejarah kolonial.',
                'location' => 'Maluku Tengah',
                'latitude' => -4.5235,
                'longitude' => 129.9024,
                'price' => 550000,
                'quota_per_day' => 100,
                'rating' => 4.8,
                'status' => 'Active',
            ],
            [
                'name' => 'Ora Beach',
                'slug' => 'ora-beach',
                'province_id' => 81,
                'category' => 'Pantai',
                'description' => 'Resort terapung dengan kejernihan air laut hingga dasar. Hidden paradise yang masih sangat alami.',
                'location' => 'Seram, Maluku',
                'latitude' => -3.0333,
                'longitude' => 129.2167,
                'price' => 650000,
                'quota_per_day' => 50,
                'rating' => 4.9,
                'status' => 'Active',
            ],
            [
                'name' => 'Kepulauan Kei',
                'slug' => 'kepulauan-kei',
                'province_id' => 81,
                'category' => 'Pantai',
                'description' => 'Pantai Ngurbloat dengan pasir terhalus di Asia. Kejernihan air dan keramahan penduduk lokal.',
                'location' => 'Maluku Tenggara',
                'latitude' => -5.6623,
                'longitude' => 132.7501,
                'price' => 400000,
                'quota_per_day' => 200,
                'rating' => 4.8,
                'status' => 'Active',
            ],
            [
                'name' => 'Morotai Island',
                'slug' => 'pulau-morotai',
                'province_id' => 82,
                'category' => 'Pantai',
                'description' => 'Pulau terluar dengan sejarah Perang Dunia II. Pantai perawan dan spot surfing yang mulai populer.',
                'location' => 'Morotai, Maluku Utara',
                'latitude' => 2.3167,
                'longitude' => 128.4333,
                'price' => 350000,
                'quota_per_day' => 100,
                'rating' => 4.6,
                'status' => 'Active',
            ],

            // PAPUA (4 lokasi)
            [
                'name' => 'Raja Ampat',
                'slug' => 'raja-ampat',
                'province_id' => 91,
                'category' => 'Laut',
                'description' => 'Surga bawah laut terbaik di dunia dengan 75% spesies karang global. Diving dan snorkeling kelas dunia.',
                'location' => 'Raja Ampat, Papua Barat',
                'latitude' => -0.2309,
                'longitude' => 130.5239,
                'price' => 1000000,
                'quota_per_day' => 200,
                'rating' => 5.0,
                'status' => 'Active',
            ],
            [
                'name' => 'Lorentz National Park',
                'slug' => 'tn-lorentz',
                'province_id' => 94,
                'category' => 'Gunung',
                'description' => 'Taman nasional terbesar di Asia Tenggara. Dari salju abadi Puncak Jaya hingga hutan bakau pesisir.',
                'location' => 'Papua',
                'latitude' => -4.5833,
                'longitude' => 137.5167,
                'price' => 800000,
                'quota_per_day' => 50,
                'rating' => 4.8,
                'status' => 'Active',
            ],
            [
                'name' => 'Lembah Baliem',
                'slug' => 'lembah-baliem',
                'province_id' => 94,
                'category' => 'Budaya',
                'description' => 'Lembah suku Dani dengan budaya asli Papua yang masih terjaga. Festival budaya dan trekking pegunungan.',
                'location' => 'Jayawijaya, Papua',
                'latitude' => -3.9672,
                'longitude' => 138.9550,
                'price' => 900000,
                'quota_per_day' => 100,
                'rating' => 4.7,
                'status' => 'Active',
            ],
            [
                'name' => 'Teluk Cenderawasih',
                'slug' => 'teluk-cenderawasih',
                'province_id' => 91,
                'category' => 'Laut',
                'description' => 'Taman nasional laut terbesar di Indonesia. Berenang bersama hiu paus dan diving yang spektakuler.',
                'location' => 'Teluk Wondama, Papua Barat',
                'latitude' => -2.1639,
                'longitude' => 134.5839,
                'price' => 750000,
                'quota_per_day' => 80,
                'rating' => 4.9,
                'status' => 'Active',
            ],
        ];

        foreach ($destinations as $dest) {
            Destination::updateOrCreate(
                ['slug' => $dest['slug']],
                $dest
            );
        }

        $this->command->info('Created/Updated ' . count($destinations) . ' ecotourism destinations!');
    }
}
